// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkTuQ4e6Ml2s5Lgy9hh_A9GOqAAWtx1qY',
    appId: '1:36976463600:web:0d2eb1ab97a5abee4b7c35',
    messagingSenderId: '36976463600',
    projectId: 'recetas-al-toque-cr',
    authDomain: 'recetas-al-toque-cr.firebaseapp.com',
    storageBucket: 'recetas-al-toque-cr.firebasestorage.app',
    measurementId: 'G-4KDTGL4BQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn-mL_ng5S-gMG4aAkIMA67ccmlhnresA',
    appId: '1:36976463600:android:eaf193602ee8349f4b7c35',
    messagingSenderId: '36976463600',
    projectId: 'recetas-al-toque-cr',
    storageBucket: 'recetas-al-toque-cr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp3yPeWpL8QLZMdl9D_kvUDjOxhd9UOU8',
    appId: '1:36976463600:ios:c56b317c05a20f424b7c35',
    messagingSenderId: '36976463600',
    projectId: 'recetas-al-toque-cr',
    storageBucket: 'recetas-al-toque-cr.firebasestorage.app',
    iosBundleId: 'com.example.recetasaltoque',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp3yPeWpL8QLZMdl9D_kvUDjOxhd9UOU8',
    appId: '1:36976463600:ios:c56b317c05a20f424b7c35',
    messagingSenderId: '36976463600',
    projectId: 'recetas-al-toque-cr',
    storageBucket: 'recetas-al-toque-cr.firebasestorage.app',
    iosBundleId: 'com.example.recetasaltoque',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkTuQ4e6Ml2s5Lgy9hh_A9GOqAAWtx1qY',
    appId: '1:36976463600:web:376bd1fc025cf3854b7c35',
    messagingSenderId: '36976463600',
    projectId: 'recetas-al-toque-cr',
    authDomain: 'recetas-al-toque-cr.firebaseapp.com',
    storageBucket: 'recetas-al-toque-cr.firebasestorage.app',
    measurementId: 'G-4SL4V1CCCP',
  );
}
